### ISSUE TITLE
Development Link

### ISSUE THREAD

**Issue by CVE82** [TULiberalArts/Temple-Neuroscience#1]
Hello Lido! Can I get a development set up/link for this repo please? Thanks so much!

**Comment by lidopaglia** [comment]
@CVE82 what should the url be?

**Comment by CVE82** [comment]
@ Lido, I believe we are going to have to redirect it to the current Temple Neuroscience Landing page, http://www.temple.edu/neuroscience/ so should it just be temple-neuroscience since we will have to redirect it anyways? Thanks!

**Comment by lidopaglia** [comment]
@CVE82 now available at http://dev.cla.temple.edu/temple-neuroscience/
