### ISSUE TITLE
Links on the University Neuroscience home page

### ISSUE THREAD

**Issue by CVE82** [TULiberalArts/Temple-Neuroscience#2]
Hey WC, we are going to need the following links in the header for the new University Neuroscience Landing page. These should replace the News, Events and Gift icon:

- [TUMail](http://tumail.temple.edu/)
- [Cherry and White](http://directory.temple.edu/)
- Search Box that has a button that leads to this link only https://search.temple.edu/search.php?searchString=Search&searchFolder=www.temple.edu%2Fneuroscience, not an open search box that you type in. 

We should also remove the College of Liberal Arts Drop Down menu as well since this is going to be the university's front facing page. 

![image](https://user-images.githubusercontent.com/15130721/47654196-b08a5800-db60-11e8-850b-69a7ff8fa06e.png)

**Comment by tu-chill** [comment]
These enhancements should be considered in the next version of tla-header. Or we should think if we need a University Level header rather than adding configuration variables into the college header.
